### ISSUE TITLE
Make Selto-Plugin use  jumps

### ISSUE THREAD

**Issue by dase78** [PawelMTRK/selto-plugin#1]
I would use this plugin heavily if it would use the `jump` command (as we have now with using the relative ruler).

In my logic `selto -5` and `selto +7` would always just mark five lines up/seven lines down from actual cursor line.

I don't know how complicated this is and if it would bother other users. If so a new comand `seltojump` could be a way. Let `selto` do what it does and make `seltojump` behave like described.

This would be a real improvement in combination with the "new" `jump`

**Comment by PawelMTRK** [comment]
Will certainly look into that!

Didn't even know relative ruler was a thing. I probably won't update it in the official micro plugin repo, since my PR is still open with no response.

If someone would wanna use updated version, they'll have to download it from the repo.

**Comment by dase78** [comment]
I don't know how much work it would be, I just can say, I would use the `selto` or `seltojump` or call it whatever you want command five days a week.

I really do not want to bother you. I think your plugin is great and when I opened my "Issue" I was surprised to be the first one to open one (because I thought "selto" is a massively used Plugin).

Just my 5c.

**Comment by PawelMTRK** [comment]
Commit cf3957379a6e10b410cf5cc5689f6e09427972c9 should have all the changes necessary to test the new command out.
Instead of naming it `seltojump`, it is `seljump` to follow the convention I used before - `selto` is `goto` with selection.

**Comment by dase78** [comment]
Wow, this works like a charm, great!

Is included now to my Defaults, thanks a lot!
